device:     "/dev/ttyUSB0"    # последовательный порт
baud:       57600            # скорость соединения
protocol:   1.0              # версия протокола Dynamixel
ids:        [2, 7, 8, 9]      # список ID сервоприводов
invert:     [1, -1, -1, 1]    # направление для каждого ID в том же порядке
speed_scale: 500 